### ISSUE TITLE
Unhelpful error message - no line number or file provided

### ISSUE THREAD

**Issue by alexzrh** [qorf/quorum-language#22]
In the case where there is some sort of selection (like if/else) where an alert happens in the else and the preceding statement, and error message is thrown "This statement would not execute, because we have already returned from the action." The issue is the line number provided is 0 and the file name provided is "TEXT" instead of the actual file.

Steps:
1. Have a small project with a Main.quorum and another file (e.g. Example.quorum)
2. In the Example file, put this code

```
if true
   alert("true")
else
   alert("false")
end
```

This error message does not happen if the if/else is in Main.

<img width="1136" alt="Screen Shot 2022-04-21 at 8 37 16 AM" src="https://user-images.githubusercontent.com/4376885/164507851-6a9d9414-5439-4f94-9049-10afa1c87d7e.png">

(Side note: you do not need a coma before the word "because" in the error message)

**Comment by andreas-stefik** [comment]
@alexzrh When I follow these instructions, I do not get an error. Can you please attach a zipped project with a reproducible test case?

**Comment by andreas-stefik** [comment]
Closed unless an example is provided. Please feel free to re-open with a reproducible example.
