### ISSUE TITLE
Misleading compiler error: "Main.quorum was specified as the starting point of the program..."

### ISSUE THREAD

**Issue by alleew** [qorf/quorum-language#27]
When running the code below, it produces a very misleading error which does not provide any context or line number to fix the actual problem. The code below will reproduce the error. The actual problem line is on line 3.

use Libraries.Compute.Statistics.DataFrame
DataFrame frame
frame Load:("data/wineReviews.csv")

**Comment by andreas-stefik** [comment]
Fixed in 13f1d73d5.
