### ISSUE TITLE
Errors on iOS and Android with Charts (more so with iOS)

### ISSUE THREAD

**Issue by kristinethellama** [qorf/quorum-language#29]
For both iOS and Android, running charts does not work. For iOS, the app launches but crashes immediately. For android, there is a compiler error. (see attached)
![blah](https://user-images.githubusercontent.com/40018813/178643755-93e5ae6e-94f4-4900-96fb-65f98a1b04a1.png)
:
This was the code we were both running:
`use Libraries.Compute.Statistics.DataFrame
use Libraries.Interface.Controls.Charts.BarChart

// create dataframe to read in data
DataFrame frame
text value = "Category,City,Country,Item,Cost
Date night,Barcelona,Spain,Dinner,69.38
Date night,New York,US,Drinks at Dinner,21.28"
        frame:LoadFromCommaSeparatedValue(value)

// pull out selected data, for this we will be catagorizing by country and cost
frame:AddSelectedFactors("Country")
frame:AddSelectedColumns("Cost")

// using the data frame, format data by creating a bar chart component
BarChart chart = frame:BarChart()

// display chart
chart:Display()`

**More issues on iOS:**
- adding a button to a game does not work and also ends up crashing the app on launch (note: this code DOES work on android, with and without a button)
ex. 
`use Libraries.Game.Game
use Libraries.Game.Graphics.Drawable
use Libraries.Game.Graphics.Color
use Libraries.Interface.Events.CollisionListener2D
use Libraries.Interface.Events.CollisionEvent2D
use Libraries.Sound.Audio
use Libraries.Interface.Controls.Button

class Main is Game, CollisionListener2D
   Drawable ground
   Drawable box
   Color color

   action Main
       StartGame()
   end

   action CreateGame
   /*
       This flag enables 2 dimensional physics for the game. Make sure to set 
       this when you want to add physics.
   */
       EnablePhysics2D(true)
       
       ground:SetName("Ground")
       ground:LoadFilledRectangle(GetScreenWidth(), 50)
       ground:SetColor(color:Green())
       Add(ground)
   /*
       We must enable physics for each Item2D object that will interact 
       with other Item2D objects.
   */
       ground:EnablePhysics(true)
   /*
       Neither gravity, collision, nor any programmatic method should be able 
       to move the ground; its responsiveness needs to be set to unmovable.
   */
       ground:SetUnmovable()

       box:SetName("Box")
       box:LoadFilledRectangle(150, 100)
       box:SetColor(color:Blue())
       box:SetPosition((GetScreenWidth() - box:GetWidth()) / 2, GetScreenHeight() - box:GetHeight())
       Add(box)
       box:EnablePhysics(true)
   /*
       The box is responds to gravity and impact with the ground, so we will 
       set to be responsive. 
   */
       box:SetResponsive()
   /*
       Finally, we set gravity 
       (This is an approximation of actual gravity)
   */
       SetGravity2D(0, -100)

       AddCollisionListener(me)

        Button button
button:ScaleFromCenter(5)
Add(button)
   end

   action BeginCollision(CollisionEvent2D event)
       output "Boom"
   end
end`

**Comment by kristinethellama** [comment]
we did not to much debugging, mostly adding the button as a control to see if it is the engine and controls causing the issue rather than the devices itself (gabe suspects this might be the issue -- engine + controls)

**Comment by sinceredevotion** [comment]
We also tried to load the data both as a .csv file and as a string, but both crashed nonetheless

**Comment by sinceredevotion** [comment]
Here is the only log I found because apparently, iOS does not make crash logs if it's on launch.

<img width="1792" alt="Screen Shot 2022-07-12 at 2 27 40 PM" src="https://user-images.githubusercontent.com/63380851/178645297-24209949-e645-4650-b68e-44e8959eea33.png">

**Comment by andreas-stefik** [comment]
This is now fixed on IOS. Turns out to have been a problem with fonts.
