### ISSUE TITLE
Where are the studies/evidence referenced? [citations needed]

### ISSUE THREAD

**Issue by sukima** [qorf/quorum-language#33]
I came across this language from this [YouTube talk](https://www.youtube.com/watch?v=uEFrE6cgVNY) and was intrigued that there was an academic field performing some studies or evidence gathering on programming language design.

In many programming circles holy wars over semantics run rampant and really lower both the developer's energy but also moral. It got me thinking that common language semantics could have evidence concerning them outside of Quorum.

> We regularly run experiments with people at various age and experience ranges, investigating ways to make the language easier to use. Evidence gathered from these studies is filtered back into the design, making quorum an "evidence-based" programming language. — [Quorum README](https://github.com/qorf/quorum-language/blob/main/README.md)

Do we have references to those studies and their conclusions? Is it possible to read and interpret these studies to gain better understanding and knowledge on the reasons for some language semantics, keywords, and design (specifically Quorum)?

**Comment by andreas-stefik** [comment]
Sure, here's a collection of some our lab runs directly:

http://web.cs.unlv.edu/stefika/publications.html

There are a ton more though on ACM digital library nowadays. Brett Becker's work, Neil Brown. Felienne Hermans, and a ton more people.

**Comment by andreas-stefik** [comment]
One other we are working on now for the language is blocks. The evidence by David Weintrop, on this issue, is pretty interesting if you don't know it.
