### ISSUE TITLE
TextFields should be quicker to update the view when the cursor moves

### ISSUE THREAD

**Issue by alleew** [qorf/quorum-language#45]
When moving the caret left or right in a TextField, the view should update as soon as the cursor exits off the left or right side of the field. Currently, it feels like the cursor needs to move slightly too far left or right before the view updates, e.g. you have to press right 1 more time than should be necessary before the view updates. This should be tweaked to feel better.

**Comment by GabeContra** [comment]
Added some changes here: 9625bbca9a044e90e5c591673cedd81d57661efd
Not perfect but definitely more usable
