### ISSUE TITLE
TextFields don't update view when navigating with HOME/END or CTRL + LEFT/RIGHT

### ISSUE THREAD

**Issue by alleew** [qorf/quorum-language#46]
When navigating text that extends beyond the width of a text field, using HOME/END or CTRL + LEFT/RIGHT (as well as their combinations with SHIFT held down) doesn't move the view to follow where the cursor ends up.

**Comment by GabeContra** [comment]
Fixed here: 9625bbca9a044e90e5c591673cedd81d57661efd
